### PR TITLE
bug fix for PR, and minor updates

### PR DESCRIPTION
**Pull request by DariuszPorowski**
- bumped GH actions to the latest in workflows and docs
- updated rule for CSCAN0220 in the toml configs
- bug fix for https://github.com/DariuszPorowski/github-action-gitleaks/issues/41 (PR issue)

### CODE REVIEW

**Comment by lawndoc** [comment]
FYI, it looks like the [PR check](https://github.com/DariuszPorowski/github-action-gitleaks/runs/6777563988?check_suite_focus=true) failed to run GitLeaks for the same reason as #41.

It shows as failing because of the Sarif report, but if you expand the "Run GitLeaks" step, it actually failed to run GitLeaks as well. It didn't fail the action in that step because of the `fail: false` flag in the workflow.

**Comment by DariuszPorowski** [comment]
@lawndoc just working on it :)

**Comment by DariuszPorowski** [comment]
@lawndoc after init draf fix, it works localy, PTAL at your side https://github.com/DariuszPorowski/github-action-gitleaks/pull/42/files#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R75

**Comment by DariuszPorowski** [comment]
btw... @lawndoc it looks like a new one official GH Action for Gitleaks has been released. https://github.com/zricethezav/gitleaks-action
So I think now is it makes sense to maintain this unofficial version?

**Comment by lawndoc** [comment]
> btw... @lawndoc it looks like a new one official GH Action for Gitleaks has been released. https://github.com/zricethezav/gitleaks-action So I think now is it makes sense to maintain this unofficial version?

I did see that... The official GH Action requires you to purchase a license to use, so there may still be a use for this one. It's up to you though on whether you want to maintain it or not.

**Pull request merged**
